/*
 * Cell Block
 * The Black Iron Software Platform is a multi-tenant SaaS coupled with an OAuth compliant authentication service that helps jump start SaaS software development.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@blackironsoftware.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AuthenticateOutput
 */
public class AuthenticateOutputTest {
    private final AuthenticateOutput model = new AuthenticateOutput();

    /**
     * Model tests for AuthenticateOutput
     */
    @Test
    public void testAuthenticateOutput() {
        // TODO: test AuthenticateOutput
    }

    /**
     * Test the property 'accessToken'
     */
    @Test
    public void accessTokenTest() {
        // TODO: test accessToken
    }

    /**
     * Test the property 'expiresIn'
     */
    @Test
    public void expiresInTest() {
        // TODO: test expiresIn
    }

    /**
     * Test the property 'idToken'
     */
    @Test
    public void idTokenTest() {
        // TODO: test idToken
    }

    /**
     * Test the property 'refreshToken'
     */
    @Test
    public void refreshTokenTest() {
        // TODO: test refreshToken
    }

    /**
     * Test the property 'tokenType'
     */
    @Test
    public void tokenTypeTest() {
        // TODO: test tokenType
    }

    /**
     * Test the property 'challengeName'
     */
    @Test
    public void challengeNameTest() {
        // TODO: test challengeName
    }

    /**
     * Test the property 'codeDeliveryMedium'
     */
    @Test
    public void codeDeliveryMediumTest() {
        // TODO: test codeDeliveryMedium
    }

    /**
     * Test the property 'codeDeliveryDestination'
     */
    @Test
    public void codeDeliveryDestinationTest() {
        // TODO: test codeDeliveryDestination
    }

    /**
     * Test the property 'userId'
     */
    @Test
    public void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'session'
     */
    @Test
    public void sessionTest() {
        // TODO: test session
    }

}
