/*
 * Cell Block
 * The Black Iron Software Platform is a multi-tenant SaaS coupled with an OAuth compliant authentication service that helps jump start SaaS software development.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@blackironsoftware.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.blackironsoftware.api;

import com.blackironsoftware.api.models.CreateRoleInput;
import com.blackironsoftware.api.models.Error;
import com.blackironsoftware.api.models.Role;
import com.blackironsoftware.api.models.Roles;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RolesApi
 */
@Ignore
public class RolesApiTest {

    private final RolesApi api = new RolesApi();

    
    /**
     * Create a role
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createRoleTest() {
        String cellId = null;
        CreateRoleInput createRoleInput = null;
        Role response = api.createRole(cellId, createRoleInput);

        // TODO: test validations
    }
    
    /**
     * Deletes a role and dissociates all users from the role.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteRoleTest() {
        String cellId = null;
        String roleId = null;
        api.deleteRole(cellId, roleId);

        // TODO: test validations
    }
    
    /**
     * Retrieve a role
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getRoleTest() {
        String cellId = null;
        String roleId = null;
        Role response = api.getRole(cellId, roleId);

        // TODO: test validations
    }
    
    /**
     * Retrieves a list of roles
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listRolesTest() {
        String cellId = null;
        Roles response = api.listRoles(cellId);

        // TODO: test validations
    }
    
}
