/*
 * Cell Block
 * The Black Iron Software Platform is a multi-tenant SaaS coupled with an OAuth compliant authentication service that helps jump start SaaS software development.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@blackironsoftware.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.Cell;
import org.openapitools.client.model.Cells;
import org.openapitools.client.model.CreateCellInput;
import org.openapitools.client.model.Error;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CellsApi
 */
@Ignore
public class CellsApiTest {

    private final CellsApi api = new CellsApi();

    
    /**
     * Create a cell
     *
     * 
     */
    @Test
    public void createCellTest()  {
        CreateCellInput createCellInput = null;
        Cell response = api.createCell(createCellInput).block();

        // TODO: test validations
    }
    
    /**
     * Deletes a cell
     *
     * 
     */
    @Test
    public void deleteCellTest()  {
        String cellId = null;
        api.deleteCell(cellId).block();

        // TODO: test validations
    }
    
    /**
     * Retrieve a cell
     *
     * 
     */
    @Test
    public void getCellTest()  {
        String cellId = null;
        Cell response = api.getCell(cellId).block();

        // TODO: test validations
    }
    
    /**
     * Retrieves a list of cells
     *
     * 
     */
    @Test
    public void listCellsTest()  {
        Integer pageSize = null;
        String pageToken = null;
        Cells response = api.listCells(pageSize, pageToken).block();

        // TODO: test validations
    }
    
    /**
     * Update a cell
     *
     * 
     */
    @Test
    public void updateCellTest()  {
        String cellId = null;
        Cell cell = null;
        Cell response = api.updateCell(cellId, cell).block();

        // TODO: test validations
    }
    
}
